baseURL = "https://writing.jinsko.com/"
languageCode = "en-us"
title = "Writing"
theme = "diary"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
  tag = "tags"

[[menu.main]]
name = "Archive"
url = "/posts/"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
  url = "/index.xml"
  name = "RSS"
  weight = 50

[params]
enableReadingTime = true